config/routes.rb
WikiSigns::Application.routes.draw do

  get "welcome/index", :as => 'welcome'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # Root
  root :to => 'welcome#index'

  match 'word/:slug', :to => 'words#show_by_slug'
  match 'word/:slug/publish', :to => 'words#publish'

  # Words
  resources :words, :except => [:destroy, :edit, :update] do
    collection do
      get  'random'
      get  'random_messages'
      get  'inspiration'
      get  'communication'
      post 'new_word'
    end

    member do
      get 'svg'
    end

    resources :games, :only => [:create, :show]
  end

  get 'threed', :to => 'threed#index'

  resources :games, :only => [:new] do
    collection do
      get  'random_word'
    end
  end
  resources :shows, :only => [:new, :show]

  resources :users, :only => [:new, :edit, :show, :update] do
    member do
      post 'daily_score'
    end
  end

  # Facebook
  post '/facebook/canvas' => 'facebook#canvas'
  filter :facebook_canvas
end

app/views/shared/_body_end.html.haml
<!-- JavaScript at the bottom for fast page loading -->
= render 'shared/javascripts'
#fb-root
= render 'shared/facebook_scripts'
= content_for :mode_script

= hoptoad_javascript_notifier if Object.const_defined?(:HoptoadNotifier)

app/views/shared/_description.html.haml
- if controller.class.eql?WordsController
  #wikisigns-description
    = t(controller.action_name, :scope => 'help')

app/views/shared/_facebook_header.html.haml
- if @word && @word.persisted?
  %meta{:property => "fb:app_id", :content => Settings.facebook.consumer_key}
  %meta{:property => "og:title", :content => ("%s @ http://WikiSigns.ch" % @word.word)}
  %meta{:property => "og:type", :content => "article"}
  %meta{:property => "og:image", :content => svg_word_url(@word, :format => 'png')}
  %meta{:property => "og:site_name", :content => "WikiSigns"}

app/views/shared/_facebook_scripts.html.haml
= javascript_include_tag 'http://connect.facebook.net/en_US/all.js'
:javascript
  window.fbAsyncInit = function() {
    FB.init({
      appId  : "#{Settings.facebook.consumer_key}",
      status : true, // check login status
      cookie : true, // enable cookies to allow the server to access the session
      xfbml  : true  // parse XFBML
    });
  };

app/views/shared/_flash_messages.html.haml
#flash-messages
  .notice
    = notice
  .alert
    = alert
    

app/views/shared/_game_menu.html.haml
#game-menu.button-link
  = link_to_function image_tag('icons/16x16/black/fast_backward.png'), 'resetGame()', :id => 'reinitialize-guessing-game', :'data-tooltip' => t('tooltip.restart')
  = link_to_function image_tag('icons/16x16/black/play.png'), 'playSessionViewer()', :'data-tooltip' => t('tooltip.session_show'), :id => 'start-session-show'
  = link_to_function image_tag('icons/16x16/black/pause.png'), 'pauseSessionViewer()', :'data-tooltip' => t('tooltip.session_pause'), :id => 'pause-session-show', :style => 'display:none;'
  = link_to_function image_tag('icons/16x16/black/fast_forward.png'), 'getANewWord()', :'data-tooltip' => t('tooltip.get_new_word')
  - if current_user && current_user.from_facebook?
    = link_to image_tag('icons/16x16/black/facebook.png'), daily_score_user_path(current_user), :remote => true, :method => :post, :'data-tooltip' => t('tooltip.post_day_score_to_fb')

app/views/shared/_head.html.haml
%meta{:charset => "UTF-8"}

<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame -->
%meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}

%title= t('title.wikisigns')
= render 'shared/facebook_header'

= csrf_meta_tag

= stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection, print'
- if params[:fb_canvas]
  = stylesheet_link_tag 'compiled/facebook.css', :media => 'screen, projection, print'

= javascript_include_tag 'cufon/cufon-yui', 'cufon/Ashby_700.font'

app/views/shared/_javascripts.html.haml
= airbrake_javascript_notifier unless Rails.env.development?
= javascript_include_tag :defaults
= javascript_include_tag 'raphael/raphael', 'raphael/word'
= javascript_include_tag 'jquery-ui-1.8.12.custom.min'
= javascript_include_tag 'jquery.shuffle', 'jquery.qtip-1.0.0-rc3', 'jquery.fancybox-1.3.4'
= javascript_include_tag 'game', 'session_show', 'show_word', 'tooltips'
// Modes
= javascript_include_tag 'random', 'welcome', 'analyze', 'communication', 'show_by_slug', 'svg'

app/views/shared/_main_menu.html.haml
.button-link
  = link_to t('navigation.left.play'), new_game_path, :id => 'new-game-link'
  = link_to t('navigation.left.analyse'), words_path, :id => 'words-link'
  = link_to t('navigation.left.communicate'), communication_words_path, :id => 'new-word-link'
  = link_to t('navigation.left.inspire'), random_words_path, :id => 'random-words-link'
  = link_to t('navigation.left.all'), inspiration_words_path, :id => 'random-words-link'
  = link_to t('navigation.left.threed'), '/threed', :id => 'threed-link'
  - unless user_signed_in?
    = link_to t('login'), user_session_path, :id => 'user-login'
  - else
    = link_to t('logout'), destroy_user_session_path, :id => 'user-logout'
  %canvas#webgl-test(style='display:none')

app/views/shared/_score.html.haml
- if 'words'.eql?controller_name
  #scores
    #last-score.score
      = t('game.last_score')
      %span
        0
    - if current_user && user_signed_in?
      #daily-score.score
        = t('game.dayly_score')
        %span
          = current_user.daily_score
      #alltime-score.score
        = t('game.total_score')
        %span
          = current_user.total_score